# Generated by Django 4.1.2 on 2022-10-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('Menuid', models.AutoField(primary_key=True, serialize=False)),
                ('MenuName', models.CharField(max_length=500)),
                ('MenuPrice', models.IntegerField()),
                ('MenuPic', models.ImageField(upload_to='')),
                ('MenuType', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('Restaurantid', models.AutoField(primary_key=True, serialize=False)),
                ('RestaurantName', models.CharField(max_length=500)),
                ('Menuid', models.IntegerField()),
                ('RestaurantSeat', models.IntegerField()),
            ],
        ),
    ]
