# Generated by Django 4.1.2 on 2022-10-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='MenuPic',
            field=models.ImageField(blank=True, upload_to='picfood'),
        ),
    ]
