# Generated by Django 4.1.2 on 2022-10-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('Reviewid', models.AutoField(primary_key=True, serialize=False)),
                ('ReviewComment', models.CharField(max_length=1000)),
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
            ],
        ),
    ]
